feign:
  httpclient:
    # 连接超时时间，单位为毫秒
    connection-timeout: 600000
    # 连接定时器重复执行的时间间隔，单位为毫秒
    connection-timer-repeat: 601000
  client:
    config:
      default:
        # 连接超时时间，单位为毫秒
        connect-timeout: 600000
        # 读取超时时间，单位为毫秒
        read-timeout: 600000
        # Feign 日志级别，可选值为 none、basic、headers 或 full
        logger-level: basic