spring:
  datasource:
    druid:
      initial-size: 3
      min-idle: 3
      max-active: 50
      test-on-borrow: true
      validation-query: SELECT 1
      filters: stat,wall
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      max-wait: 5000
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000
      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        allow: null
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: F&8%*Ak+
        enabled: true

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.fast.start
  global-config:
    # 数据库相关配置
    db-config:
      #驼峰下划线转换
      table-underline: true
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    local-cache-scope: statement