spring:
  application:
    name: fast-system
  datasource:
      url: jdbc:mysql://192.168.93.27:3308/fast_cloud_demo?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
server:
  port: 8081
app:
  swagger:
    enable: @app.swagger.enable@
swagger:
  base:
    package: @swagger.base.package@
